version: "3.9"

services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgres-learnings"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - mydata:/data/postgres-learnings
    ports:
      - "5432:5432"
    restart: unless-stopped
  pgadmin:
      image: dpage/pgadmin4:6
      container_name: pgadmin4_container
      environment:
        PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
        PGADMIN_LISTEN_PORT: 5050
      ports:
        - "5050:5050"

volumes:
    mydata:
      external: true