spring:
  application:
    name: GraphQL-Server
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/learnings
    username: learner
    password: password